import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import React  from 'react';
import store from './store';
import { Provider } from 'react-redux';
import TodoList from './src/TodoList';
import { ThemeProvider } from 'styled-components'
import Theme from './src/styled/theme';

const Home: NextPage = () => {

  return (
    <Provider store={store}>
      <ThemeProvider theme={Theme}>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            {/* <AddItem />
            <ListTodo data={state?.data} /> */}
            <TodoList />
          </main>

          {/* <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
              <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            </a>
          </footer> */}
        </div>
      </ThemeProvider>
    </Provider>
  )
}

export default Home
